### ISSUE TITLE
Add entry for admin page

### ISSUE THREAD

**Issue by beckyqiu** [TF3FAN/CodeU-Summer-2018#5]

**Comment by Gjain234** [comment]
<img width="1007" alt="screen shot 2018-06-25 at 6 05 59 pm" src="https://user-images.githubusercontent.com/25145128/41883480-9e53f0d0-78a3-11e8-9aaf-710863902a82.png">
<img width="1026" alt="screen shot 2018-06-25 at 6 05 44 pm" src="https://user-images.githubusercontent.com/25145128/41883481-9e7bc1f0-78a3-11e8-84a8-96a9ef68da23.png">

Does an entry point like this look okay?

**Comment by beckyqiu** [comment]
LGTM! Thanks!
